### ISSUE TITLE
[Reporters] add a fault tolerant (ignore) mode to the JSON parser

### ISSUE THREAD

**Issue by lorenzofox3** [lorenzofox3/zora#108]
see https://github.com/lorenzofox3/zora/discussions/107#discussioncomment-1373386 for more details

**Comment by mindplay-dk** [comment]
I don't know how this would work?

I mean, what happens if my application actually prints out JSON?

Some solutions that sound more appropriate to me: run the reporter in-process, or send your debug to `stderr` instead of `stdout` - for example, I just learned that `Console` actually has a [constructor](https://nodejs.org/api/console.html#console_new_console_options) that would let you redirect everything to `stderr`.

I'm not sure allowing for the mixing of unrelated streams is really the answer - if you're going to work with streams, you should probably design for that. Streams kind of seems like that should be the "advanced" option, while a simple in-process reporter is probably easier for most people to understand? It is for me, at least - I'm kind of a Linux idiot. 🙂
