### ISSUE TITLE
Diff reporter doesn't display assertion messages

### ISSUE THREAD

**Issue by mindplay-dk** [lorenzofox3/zora#112]
I carefully describe most of my assertions like this:

![image](https://user-images.githubusercontent.com/103348/136159180-e745902f-388a-4912-9380-0ab38f959962.png)

With the diff reporter, these aren't currently displayed anywhere:

![image](https://user-images.githubusercontent.com/103348/136159240-dbb29692-91b0-4e55-a163-1403b3475cda.png)

With tap-diff, my test output was like a written specification - I've kind of lost that.

I'm sure this must be an oversight and not by design? The assertion messages are part of zora's assertion model after all.

Perhaps a verbosity option might be appropriate as well? Again, with tap-diff, I was able to produce a full "written spec" from my test-suite, whereas the diff reporter works more like the "pessimist" type tap reporters. There are times when you want to see everything your test covers, when you want written confirmation that all your tests are being run, and so on.

(don't get me wrong, I'm not longing for tap-diff - it had plenty of problems, and the diff reporter is generally much more useful.)

And let me know if I can help with any of that? 🙂

**Comment by lorenzofox3** [comment]
Yes, we should print the test description [somewhere there](https://github.com/lorenzofox3/zora/blob/master/reporters/src/diff/writer/index.js#L17-L20)

**Comment by tsnobip** [comment]
I'd be pretty interested in having the description in the diff reporter too, what's the current state of the PR, do you need help @mindplay-dk?

**Comment by mindplay-dk** [comment]
@tsnobip I haven't gotten back to this - I don't have the time and attention this requires right now, sorry.

@lorenzofox3 this area of the codebase doesn't seem immediately very contributor friendly? I would suggest using IOC for the print functions, but that might require a breaking change (?) and at least some refactoring work?

I would love to help but working through this crazy console output is more overhead than I can manage atm...

**Comment by lorenzofox3** [comment]
> @lorenzofox3 this area of the codebase doesn't seem immediately very contributor friendly? I would suggest using IOC for the print functions, but that might require a breaking change (?) and at least some refactoring work?

You mean getting injected some sort of console abstraction like in the tap reporters ? 🤔 

That is not really the problem here and the added value would be very low I think. 

I think, the main issue in this area is the explosion of cases and the branching. That's why I believe splitting the code base between pure functions which return small part of the text stream, and the actual side effect (print), is a good strategy. 
Abstracting the "printer" would not solve the problem. 

Obviously there are holes in the racket and this would require integration testing to be complete but that is lot of work to catch very few bugs/regressions.

Eventually we could consider a plugin based archi where the reporter is in charge of the branching and the plugins hook themselves to print/generate the message in a very specific case.

> I would love to help but working through this crazy console output is more overhead than I can manage atm...

I'll do it then or @tsnobip if you wish to ?

**Comment by tsnobip** [comment]
to be honest I don't know if I'll have time for that right now, especially given we're questioning the use of zora for our use case at work (I think it's really great and would give anything to get rid of Jest machinery but we need snapshot testing unfortunately 😞)
