### ISSUE TITLE
t.throws and t.doesNotThrow should be able to accept a promise

### ISSUE THREAD

**Issue by jaydenseric** [lorenzofox3/zora#18]
At the moment, `t.throws` and `t.doesNotThrow` only accepts a function. It should also be able to accept a promise, [like AVA](https://github.com/avajs/ava#throwsthrower-expected-message).

I want to be able to test that Koa middleware throws a particular error:

```js
(ctx, next) => {
  t.throws(next(), MyError)
}
```

It would be great if the function return value and promise resolved value would be returned. Here is an AVA example:

```js
const promise = Promise.reject(new TypeError('🦄'));

test('rejects', async t => {
  const error = await t.throws(promise);
  t.is(error.message, '🦄');
})
```

**Comment by lorenzofox3** [comment]
Looks like nice syntactic sugar addition ! 

Quick question, how would you deal with rejected promise (no error thrown) ?

Would like to make a PR ? I think that is an easy addition [here](https://github.com/lorenzofox3/zora/blob/master/lib/assertions.js#L63)

**Comment by oles** [comment]
>Looks like nice syntactic sugar addition !

I can't seem to figure out how to do do this without the syntax sugar.

Tried various examples from https://github.com/substack/tape/pull/351, but I can't make any of them work as expected. 

```
test('throw promise', async assert => {
    try {
        await promiseThatThrows()
    } catch(error) {
        console.log(error)        
    }

    console.log("after")
})
```

Neither the error nor "after" is logged out :thinking:

**Comment by lorenzofox3** [comment]
I think you are mislead by console.log. As tests run in parallel the logging sequence (at least through console.log) is not relevant.

However you should be able to test promise error easily 

```Javascript
const throwing = async (message) => {
  throw new Error(message);
}

test('test 1',async t => {
  try {
    await throwing('oh no!');
  } catch (e){
    t.equal(e.message,'oh no!', 'should test the error');
  }
  
  t.ok(true,'shoud run after');
});
```
or [in action](https://codepen.io/lorenzofox3/pen/jKpBMj?editors=1112)

**Comment by oles** [comment]
Sweet, thanks for the example! I'll try it out soon :+1:

**Comment by mindplay-dk** [comment]
⚠ warning: the example above will always pass - even if `throwing` does not throw!

✔ The correct solution was offered in [this thread](https://github.com/lorenzofox3/zora/issues/66#issuecomment-665503325).

I do think we have a problem with this feature... I fall into this trap myself every time - the issue has been posted twice now, and the track record for someone providing the correct workaround is 1:2. 😉

**How about the following solution?**

1. If the callback passed to `throws` returns a `Promise`, it should throw an error and abort the test: this will help folks realize that `throws` is *not* intended for use with async callbacks - currently this quietly fails, so this will fix that.

2. Add a another assertion `rejected` specifically accepting *only* a `Promise`, which must be rejected rather than resolved: this is more explicit and makes the distinction more clear.

When failing in `throws` for passing a `Promise`, the error message could explain how to correctly switch to `rejects`, e.g.:

    await t.rejected(async () => { .... })

We should tighten the type-hints in TS as well - for `throws` we can use a param type `T extends Promise<unknown> ? never : T`, as covered in [this article](https://levelup.gitconnected.com/how-is-promise-t-be-assignable-to-t-f147d13d1e76), and for `rejected` of course this would accept solely a `Promise<T>`.

(The only remaining pitfall then is people may forget to use `await` with `t.rejected` - but that's just Javascript, I'm afraid.)

What do you think, would you consider reopening this issue?
