### ISSUE TITLE
How to know when all tests have completed?

### ISSUE THREAD

**Issue by coolaj86** [lorenzofox3/zora#189]
I know this is mostly intended for unit tests, but I also have some tests to run that do DB calls.

Is there a way to know when all async functions have completed as to close the DB connection so the test file can exit?

**Comment by lorenzofox3** [comment]
you'll need to start the reporter yourself, or create a custom test harness. I could probably add an event as well. 

have a look at [pta cli file](https://github.com/lorenzofox3/zora/blob/master/pta/src/bin.js#L68-L87) if you want an example.

for your usecase, I usually wrap the default test function into a custom one which setup db and close it after each test. 

It allows me for example to inject a custom db service which run every single test in an isolated transaction so that I can run all the tests concurrently. 

here with pg

```Javascript
import { test as ztest } from 'zora';
import { createDB } from 'db';
import { baseConfig, testDB } from './_config.js';

const testController = new AbortController();
const testClient = createDB({
  ...baseConfig,
  transactionMode: 'no-commit',
  database: testDB,
  signal: testController.signal,
  allowExitOnIdle: true,
  max: 10,
});

export const test = (description, specFn, options) =>
  ztest(
    description,
    (assert) => specFn({ ...assert, db: testClient }),
    options
  );
```

and then I use this test function rather than zora's one
