### ISSUE TITLE
feature: support Buffer comparison in `same()` function

### ISSUE THREAD

**Issue by mikeal** [lorenzofox3/zora#39]
Currently, zora just aliases `same` to `is`. In `node-tap` the same function is a much more sophisticated comparison that does deep object comparison and supports comparison of Buffers and other binary objects.

I tried to swap out `node-tap` for `zora` in order to get browser support and immediately hit this problem.

**Comment by mikeal** [comment]
Looks like this is already broken out into its own module https://github.com/tapjs/tsame#readme

**Comment by lorenzofox3** [comment]
``is``  follows the Ecmascript Standard semantic of ``Object.is`` so it does a reference check on object like structure (like buffers). I think what you are looking for is ``eq`` which does a content check. See the [codepen](https://codepen.io/lorenzofox3/pen/BEYGNq?editors=1111). Sorry for the confusion it brings.

**Comment by mikeal** [comment]
I think the confusion stems from aliasing `same` to `is`. In `node-tap` the semantics are quite different and if this is meant to be a dropin replacement that probably needs to change as well.

**Comment by lorenzofox3** [comment]
Yes you are right. But I guess it is matter of preference. For me, I understand ``same``  as "are we talking about the same thing ?" (hence the reference check) and it will be different for someone else I guess.

> In node-tap the semantics are quite different and if this is meant to be a dropin replacement that probably needs to change as well.

That is not the case. V2 of zora was meant to be a drop in replacement for tape in order to gain traction. As it did not succeed, I just decided to drop any legacy to focus on code quality and fulfill the goal of the project: now zora is only a fast EcmaScript test program platform agnostic.
