### ISSUE TITLE
JS-DOM support (or recipe?)

### ISSUE THREAD

**Issue by mindplay-dk** [lorenzofox3/zora#56]
Hey, this project looks pretty exciting! Seems like a spiritual successor to `tape` but written in TypeScript with zero dependencies, great performance, and built-in support for Promises. Yay! 🤩

I've been trying to write a test using `jsdom-global`, and for the moment just doing this:

```js
import { test } from "zora";
import useDOM from "jsdom-global";

test("all that jazz", async (is) => {
  const cleanDOM = useDOM();

  document.body.appendChild(document.createElement("div"));

  is.equal(document.body.children.length, 1);

  cleanDOM();
});
```

This is rather fragile and not very elegant.

I didn't find anything in the README or your [recipes list](https://github.com/lorenzofox3/zora/issues/50) - is there a cleaner way to go about this?

I did try writing a helper function like this:

```js
import useDOM from "jsdom-global";

export const withDOM = test => async () => {
  const cleanDOM = useDOM();

  const result = await test();

  cleanDOM();

  return result;
};
```

But first off, if I wrap my test-function in this, the IDE support and auto-completion is gone, since this particular project doesn't use TypeScript.

And even if I was willing to put up with that, for some reason the test just runs right through without any assertions.

I did get [something like this](https://github.com/mindplay-dk/fre/blob/use-tape/test/hello.test.js) working with `tape` and it's possible I'm being a doofus here and somehow creating a [timing issue](#55), not sure.

Do you know of a project with a test-suite using JS-DOM that I could look at?

**Comment by mindplay-dk** [comment]
Let me share what I've learned so far.

`jsdom-global` apparently is unmaintained and outdated - so I've scrapped that and I'm now using plain `jsdom` instead, which takes a bit more footwork:

```js
import { JSDOM } from "jsdom"

export function withDOM(test) {
  return async (...args) => {
    const dom = new JSDOM('')

    const { window } = dom

    global.window = window
    global.document = window.document

    global.requestAnimationFrame = setTimeout
    global.cancelAnimationFrame = clearTimeout

    copyProps(window, global)

    const result = test(...args)

    // TODO clean up globals??

    return result
  }
}

function copyProps(src, target) {
  Object.defineProperties(target, {
    ...Object.getOwnPropertyDescriptors(src),
    ...Object.getOwnPropertyDescriptors(target),
  })
}
```

I based this on a solution I found in the [enzyme docs](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md).

This is a decorator for your test-functions, so use it like this:

```js
test("my test", withDOM(t => {
  // ...
}));
```

The project I'm testing is plain JS, so the big drawback right now, is no IDE support for assertion methods - for that, we'll need a proper TS package, I guess.

Also, this currently leaves behind a trailing mess of globals, which really should be cleaned up... ideally, we shouldn't be relying on global state in the first place, but I'm not sure yet how we can get around that... definitely open to ideas here...

(Any interest from the maintainer in solving this?)

**Comment by lorenzofox3** [comment]
zora is platform agnostic and should work with any library. The only thing to keep in mind is that tests run in parallel by default so if you rely on some sort of global state, you may have to run your tests in sequence if you don't want to mess that shared state

```javascript
test(`some test in sequence`, async t => {
    let state = 0; // some shared state

    // waiting for the test to finis before moving on
    await t.test(`first`, t => {
        t.eq(++state, 1);
    });

    // waiting for the test to finis before moving on
    await t.test(`first`, t => {
        t.eq(++state, 2);
    });

    // etc
    await t.test(`first`, t => {
        t.eq(++state, 3);
    });
});
```

regarding some boilerplate you want to avoid, using a decorator function is a good choice. Some details in #52 

For integration with IDE, I am not sure to understand but you can write your decorator in typescript.

>Also, this currently leaves behind a trailing mess of globals, which really should be cleaned up... ideally, we shouldn't be relying on global state in the first place, but I'm not sure yet how we can get around that... definitely open to ideas here...

Just run your test in sequence and call a tear down function after each test has run.

Generally speaking:
If you want a browser environment, why do you rely on JSDOM ? with zora you can run your tests transparently in the browser directly. 

If you keep wanting using node, you can have a look at [pta](https://github.com/lorenzofox3/zora-node)

**Comment by mindplay-dk** [comment]
> zora is platform agnostic and should work with any library. The only thing to keep in mind is that tests run in parallel by default so if you rely on some sort of global state, you may have to run your tests in sequence if you don't want to mess that shared state

I sort of wish this feature was opt-in rather than opt-out - to avoid that, currently, I'd have to wrap my entire test-suite in a single parent test, right?

Technically, I could write the entire library using dependency injection for all the browser globals, and the tests *could* run in parallel with separate instances of `JSDOM`.

But I'm also hoping to run these tests against a real browser at some point down the line, where dependency injection isn't possible - so the tests have to run sequentially in the browser at least... I might need a small custom test-harness at that point...

To your knowledge, has anyone tried to run zora in a real (or headless) browser yet?

> For integration with IDE, I am not sure to understand but you can write your decorator in typescript.

The project I'm testing is plain JS - I might write a TS version and package it properly with tests at some point down the line, but for now, calling a decorator function comes at the cost of parameter type inference and IDE support for `t.*` ... that's okay for now, I think.

**Comment by lorenzofox3** [comment]
>I sort of wish this feature was opt-in rather than opt-out

Sorry but this is by design and won't change:
- It allows to run all the tests concurrently by default which gives top notch performances
- It enforces user to write atomic tests which is often a good practice (especially for unit testing)

Yet you can control the execution flow if it is necessary as I showed you or as you can read in the readme

>to avoid that, currently, I'd have to wrap my entire test-suite in a single parent test, right?

Again it depends on your needs. Consider every test you write will run in isolation. If for some reasons you need to introduce some dependency between some tests or control the execution order, you can create a parent test and suspend the execution with the ``await`` keyword as I showed earlier. The key point is you can wait for a sub test to complete before moving on.

>Technically, I could write the entire library using dependency injection for all the browser globals, and the tests could run in parallel with separate instances of JSDOM.

that is indeed possible, but I think you are over complicating thing. You can use tools such [puppeteer](https://www.npmjs.com/package/puppeteer) which allows you to create sand boxed context with frame, etc. 

I think it would help a lot if you could set up a minimal example (gist ?) with a function you want to test and the problems you are facing...

>But I'm also hoping to run these tests against a real browser at some point down the line, where dependency injection isn't possible - so the tests have to run sequentially in the browser at least... I might need a small custom test-harness at that point...

Again, that is not sure at all. If your test are not messing with each other you could run them concurrently. 

>To your knowledge, has anyone tried to run zora in a real (or headless) browser yet?

Yes, I do it all the time I write a library for the browser. And by the way, there is an example in the readme. For CI it uses tape-run which uses ... JSDOM :) Nowadays, I find easier to automate with puppeteer. 

[test web components](https://github.com/citykleta/ui-kit)
[another one with screen shots](https://github.com/Citykleta/mapboxgl-webcomponent)
[an older one](https://github.com/smart-table/flaco)
[from another user which tests webgl application](https://github.com/lorenzofox3/zora/issues/47)
[in a codepen](https://codepen.io/lorenzofox3/pen/zoejxv)

Again, the easiest would be you to provide some (minimal) example.

You can also have a look at [this project under construction](https://github.com/lorenzofox3/zora-dev-server). The idea is to run a dev server with special endpoints to run test files for development. Then for automation, you can "visit" these endpoint with the tool of your choice (puppeteer, karma, etc)

>The project I'm testing is plain JS - I might write a TS version and package it properly with tests at some point down the line, but for now, calling a decorator function comes at the cost of parameter type inference and IDE support for t.* ... that's okay for now, I think.

This is not really related to zora but more to your tooling. I have no issue with my IDE for example:

<img width="496" alt="Screenshot 2019-12-17 at 15 30 32" src="https://user-images.githubusercontent.com/2402022/71037963-c8b79080-20ee-11ea-9945-7ef01769f81b.png">

<img width="524" alt="Screenshot 2019-12-17 at 15 31 31" src="https://user-images.githubusercontent.com/2402022/71037973-ce14db00-20ee-11ea-88b8-91dd2c73aac3.png">

**Comment by mindplay-dk** [comment]
Thank you for covering all my questions in depth!

> And by the way, there is an example in the readme. For CI it uses tape-run which uses ... JSDOM :)

For the record, I've read the README several times over - I'm not that guy who starts asking questions before looking at the docs, I promise 😉

But I don't see JSDOM referenced anywhere in the README? I also don't see it mentioned in the `tape-run` docs, and `tape-run` doesn't depend on `jsdom`. I also don't see `jdsom` being used in any of the examples you linked to, so I can't seem to find what you're referring to here...

> > to avoid that, currently, I'd have to wrap my entire test-suite in a single parent test, right?
>
> Again it depends on your needs. Consider every test you write will run in isolation.

In "isolation", I'm not sure what you mean?

Every test runs in the same environment, right? They're just async closures going into a stream, as far as I can tell? So they all run in one thread and have access to the same globals, is that not correct?

To be clear, if I want to use `jsdom` (and assuming I use globals rather than dependency injection) is there another option besides wrapping my entire test-suite in a single parent test?

For the record, I'm testing a React-like [UI framework](https://github.com/yisar/fre) which uses a single browser-wide queue and scheduling mechanism to schedule updates - so it's manipulating a single DOM via globals like `document`, which is already causing me problems, e.g. two tests passing individually, but failing randomly when run together. Any other ways around this besides putting everything in a parent test or using DI to inject unique instances of JSDOM?

(Thanks for your patience!)

**Comment by lorenzofox3** [comment]
>But I don't see JSDOM referenced anywhere in the README? I also don't see it mentioned in the tape-run docs, and tape-run doesn't depend on jsdom. I also don't see jdsom being used in any of the examples you linked to, so I can't seem to find what you're referring to here...

You are right, my bad. I confused Electron (the headless browser used by default within ``tape-run``) with JSDOM.

> Every test runs in the same environment, right? They're just async closures going into a stream, as far as I can tell? So they all run in one thread and have access to the same globals, is that not correct?

It **is** correct. What I meant is that when you write a test, you should write it as if it was isolated from the rest of your tests without expecting any order of execution... unless you want to specifically control that order with ``async/await`` flow in a parent test spec function.

>To be clear, if I want to use jsdom (and assuming I use globals rather than dependency injection) is there another option besides wrapping my entire test-suite in a single parent test?

That is where it is not clear. If you need to "write" to a global state and depends on that result, yes that would help. (see example below).

>For the record, I'm testing a React-like UI framework which uses a single browser-wide queue and scheduling mechanism to schedule updates - so it's manipulating a single DOM via globals like document, which is already causing me problems, e.g. two tests passing individually, but failing randomly when run together. Any other ways around this besides putting everything in a parent test or using DI to inject unique instances of JSDOM?

Unfortunately this is not precise enough for me to help but you can have a look at the following example. 

Consider the following task based renderer a framework could use:
<details>
    <summary>renderer.js</summary>

```Javascript

const fakeRendererToBeTested = (window = window) => {
    const tasks = [];
    const {document} = window;
    let flush = null;
    let pending = null;
    const instance = {
        [Symbol.asyncIterator]() {
            return this;
        },
        async next() {
            if (pending) {
                await pending;
                pending = null;
                return this.next();
            }

            const task = tasks.shift();
            await new Promise(resolve => window.requestAnimationFrame(() => {
                try {
                    const el = document.getElementById(task.id);
                    task.task(el);
                } catch (e) {
                    // whatever
                } finally {
                    resolve();
                }
            }));

            if (tasks.length === 0) {
                this.suspend();
            }

            return {
                done: false,
                value: task
            };
        },
        enqueueTask(id, task) {
            // remove any pending job related to the element;
            const index = tasks.findIndex(i => i.id === id);
            if (index !== -1) {
                tasks.splice(index, 1);
            }
            tasks.push({id, task});

            if (tasks.length === 1) {
                this.resume();
            }
        },
        suspend() {
            pending = new Promise(resolve => {
                flush = () => resolve();
            });
        },
        resume() {
            if (flush) {
                flush();
                flush = null;
            }
        }
    };

    instance.suspend(); //init

    return instance;
};
```

</details>

It does not use DI but something comparable. I think it will help the tests, especially as it deals with globals: One can swap for a fake implementation of ``window`` when unit testing while keeping a real browser env for integration tests.

Now, consider the following test decorator:

<details>
    <summary>test-decorator.js</summary>

```Javascript
const withSandbox = specFunction => async t => {
    const iframe = document.createElement('iframe');
    iframe.src = 'about:blank';
    document.querySelector('body').appendChild(iframe);
    const window = iframe.contentWindow;
    await specFunction(t, window, window.document.querySelector('body'));
    // clean up if is important
    iframe.remove();
};
```

</details>

It uses Iframes but you can use JSDOM if you prefer.

Now you can still write your test concurrently like so:

<details>
<summary>test.js</summary>

```javascript
const generateId = (function*(){
    let i=0;
    while (true){
        yield ++i;
    }
})();

test(`renderer`, withSandbox(async (t, window, body) => {

    const t1 = t.test(`should process task as they enter`, async t => {
        const {document} = window;
        const renderer = fakeRendererToBeTested(window)[Symbol.asyncIterator]();
        const el1 = document.createElement('div');
        const el2 = document.createElement('div');
        el1.id = generateId.next().value;
        el2.id = generateId.next().value;
        body.appendChild(el1);
        body.appendChild(el2);

        renderer.enqueueTask(el1.id, el => el.textContent = 'hello');
        renderer.enqueueTask(el2.id, el => el.textContent = 'world');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, '');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, 'world');
    });

    const t2 = t.test(`should modify task before it is processed`, async t => {
        const {document} = window;
        const renderer = fakeRendererToBeTested(window)[Symbol.asyncIterator]();
        const el1 = document.createElement('div');
        const el2 = document.createElement('div');

        el1.id = generateId.next().value;
        el2.id = generateId.next().value;

        body.appendChild(el1);
        body.appendChild(el2);

        renderer.enqueueTask(el1.id, el => el.textContent = 'hello');
        renderer.enqueueTask(el2.id, el => el.textContent = 'world');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, '');

        renderer.enqueueTask(el2.id, el => el.textContent = 'woot');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, 'woot');
    });

    // wait for the two concurrent tests to complete before cleaning
    await Promise.all([t1, t2]);
}));
```
</details>

And it will work perfectly although they share the same context because the tests and the tested code do not "write" to the global state.

NB: If the last line bother you, you can include it in the decorator making sure every ``t.test`` collect the result and the decorated function returns the list of collected test

Now if you wish to reuse the same instance of the renderer and the same elements, you will need to run the tests in sequence.

<details>
<summary>test.js</summary>

```javascript
test(`renderer`, withSandbox(async (t, window, body) => {
    const {document} = window;
    const renderer = fakeRendererToBeTested(window)[Symbol.asyncIterator]();
    const el1 = document.createElement('div');
    const el2 = document.createElement('div');
    el1.id = 'el1';
    el2.id = 'el2';
    body.appendChild(el1);
    body.appendChild(el2);

    //wait for that one to finish
    await t.test(`should process task as they enter`, async t => {

        renderer.enqueueTask(el1.id, el => el.textContent = 'hello');
        renderer.enqueueTask(el2.id, el => el.textContent = 'world');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, '');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, 'world');
    });

    await t.test(`should modify task before it is processed`, async t => {

        el1.textContent = '';
        el2.textContent = '';

        renderer.enqueueTask(el1.id, el => el.textContent = 'hello');
        renderer.enqueueTask(el2.id, el => el.textContent = 'world');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, '');

        renderer.enqueueTask(el2.id, el => el.textContent = 'woot');

        await renderer.next();

        t.eq(el1.textContent, 'hello');
        t.eq(el2.textContent, 'woot');
    });
}));
```
</details>

Both example rely on the decorator which somehow mix the "how to run the tests"  vs "what to run". If you are working on an entire framework, you should probably build a small test runner on top of zora and solving the "how" at the test runner level, and it that case you have many different solutions: 
* serving each file within an Iframe 
* use a tool like puppeteer and start each test on its own frame.
* spawning child processes with a different instance of JSDOM

etc..

It is difficult to say what would be the best solution for your use case as I don't know much about it.

As it is, zora already "supports" iframe, JSOM, etc. It depends mostly on how you architect your tests. If you are looking for a more all baked in solution, that would be the purpose of other packages. Zora Dev Server is one of them but still under development

**Comment by mindplay-dk** [comment]
Amazing answer, thank you so much!

You might consider copying this to a wiki or something? Or the recipes list you have planned. 🙂
