### ISSUE TITLE
Option to run in serial/sequential mode for integration tests?

### ISSUE THREAD

**Issue by icetbr** [lorenzofox3/zora#67]
Hi, I wonder if you considered this? I have thousands of integration tests, not that I need Zora, but were I to have started using it in the first place, it would be nice if it were a choice, instead of marking every test with `await`. I run them separated from my unit tests.

**Comment by lorenzofox3** [comment]
Hello and thanks for your feedback. 

There is no plan to have this option (it was included in the first version of zora but not so of use). I'll have a look if we can have the expected behavior by creating a custom test harness and using a decorator. I believe it could be possible in some way. I'll keep you posted
