### ISSUE TITLE
Unhandled exceptions

### ISSUE THREAD

**Issue by davidrot** [lorenzofox3/zora#68]
Hello, 

I'm having following problem when having unhandled exceptions. I'm not sure if this is a problem of zora or from the reporter...

This is my test code 
```
test('testgroup', t => {
    t.test('test', t => {
        throw "test"
    });
});
```

Result:
```
TAP version 13
# testgroup
# test
Bail out! Unhandled error.
(node:56299) UnhandledPromiseRejectionWarning: test
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I would expect something like

```
TAP version 13
# testgroup
# test

Exception: "test"
Stacktrace: " /Users/david/dev/svelte-micro-router/public/test/src/router/Router.node.spec.js:15:11"
1..1
```

I also having this problem when i try to pipe the output to some other reporter. For example: I'm wondering why 0 failed tests?
It is not easy to see where the exception comes from.

```
▶ node public/test/src/router/Router.node.spec.js | npx tap-dot 
(node:56371) UnhandledPromiseRejectionWarning: test
(Use `node --trace-warnings ...` to show where the warning was created)
(node:56371) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:56371) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

  2 tests
  0 passed
  0 failed  

  Failed Tests:   There were 0 failures
```

**Comment by davidrot** [comment]
<img width="1178" alt="zora" src="https://user-images.githubusercontent.com/5358167/93016110-0df5e980-f5bf-11ea-9fd0-e94e43d3d6c7.png">

Here is a another example, somehow the reporter thinks that the stats are some unit tests...

**Comment by lorenzofox3** [comment]
Hello and thanks for the feedback. 

When there is an unhandled error, zora ``bail out`` which is part of the [TAP specification](http://testanything.org/tap-specification.html) and is the expected behavior

Unfortunately, Nodejs does not report properly yet the stacktrace on unhandled promise rejection (see deprecation warning). 
You can still have this information if you run the program with the ``--trace-warnings`` flag (ex ``node --trace-warnings mytest.js``)

<img width="1006" alt="Screenshot 2020-09-13 at 13 24 39" src="https://user-images.githubusercontent.com/2402022/93016858-84e1b100-f5c4-11ea-8089-fd5942cbab37.png">

Finally the wrong plan is due the tap reporter you use downstream and need to be fixed there.

[A member of the community has already fixed a pair of reporters](https://github.com/lorenzofox3/zora/issues/20#issuecomment-594003373)

**Comment by lorenzofox3** [comment]
I am closing this one as I am not sure there is any action we should take on the zora side
