### ISSUE TITLE
Linting has problems with unhandled Promises

### ISSUE THREAD

**Issue by martinheidegger** [lorenzofox3/zora#79]
`test(...)` [returns a promise](https://github.com/lorenzofox3/zora/blob/4f89309b9c384477f91de846936db1af2c4f8499/src/interfaces.ts#L52) and when I lint with [`ts-standard`](https://github.com/standard/ts-standard) the error occurs that there is a dangling promise:

```
ts-standard: Typescript Standard Style! (https://github.com/standard/ts-standard)
   test.ts:4:1: Promises must be handled appropriately or explicitly marked as ignored with the `void` operator. (@typescript-eslint/no-floating-promises)
```

For now its a workaround to disable `no-floating-promises` for the test file but this will also skip the linting test for sections I don't use and adding one for each test seems tedious.

Is there a better way to avoid this issue?

**Comment by lorenzofox3** [comment]
That is actually on purpose: you can explicitly await the promise to resolve if you want the tests to run serially otherwise the result promise is simply ignored so the tests can run concurrently. Therefore, I can not change the returned type as it is the expected behaviour. So yes, I think you should either disable the rule for the test files (I think you can do it globally according to a glob ``test/**/*.ts`` and do not have to put it in every file; or as suggested in the error you can add a void before the tests you want to run concurrently

```Javascript
t.test('some test', t => {
   // concurrently
    void t.test('foo', /* ... */)

   // concurrently
    void t.test('foo', /* ... */)

   // the next depends on this one (serial)
   await t.test('foo', /* ... */)

   await t.test('foo', /* ... */)
})
```

**Comment by martinheidegger** [comment]
Thanks for looking into it.
